### PR TITLE
Run the Docker image directly, without docker-compose

### PR DESCRIPTION
**Pull request by mogul**
Speeds up iteration on `make down; make build ; make up`!

### CODE REVIEW

**Review by srinirei — DISMISSED** [review]
We paired through this.

**Comment by mogul** [comment]
We didn't test it well enough! When the GitHub Action runs `make build up wait test`, the `test` target just barrels on right after `up` even though the broker isn't ready yet. It turns out we still need to wait, even with SQLite; it still takes a while after the completion of `up` before the CSB is actually ready to accept requests, just not as long. (We also accidentally removed the `wait` target so it wasn't doing anything... 😳 🤦 )

I took the time to figure out how to add a proper healthcheck in Docker, and then added a one-line loop that waits for the csb-service to become healthy. Error-checking is not great, but now it's very accurate in terms of delaying for just the right amount of time, and no more.

**Comment by mogul** [comment]
Oh, and I cleaned up the Makefile output a bit so it will be easier to scan the output of a GitHub Action run.

**Comment by mogul** [comment]
I made [a feature request to add a HEALTHCHECK line to the Dockerfile](https://github.com/pivotal/cloud-service-broker/issues/149) upstream.

**Review by srinirei — APPROVED** [review]
Paired through this

**Pull request merged**
