### PR TITLE
Add Solr Operator Authentication

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Attempt to fix https://github.com/GSA/datagov-deploy/issues/3274 based on Bret's guidance.

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
The tests don't get past the second provisioning on Github Actions, I added in the tmate stuff to debug it, but it needs to be merged into main before we can utilize it.  For sanity, the tests pass locally for me.  @mogul @robert-bryson Can one or both of you test it locally to make sure I don't have any unique configuration for right now?
`make test-env-down test-env-up .env down build up test`  should do it 😅 

```
nickumia@DL62-2-2MDD043:~/datagov-brokerpak$ git push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 557 bytes | 557.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:GSA/datagov-brokerpak.git
   0ef699b..b95bf95  feature/solr-authentication -> feature/solr-authentication
nickumia@DL62-2-2MDD043:~/datagov-brokerpak$ make test
sudo chmod 766 /etc/hosts
bats test.bats
 ✓ examples.json exists
 ✓ provision 1 works
 ✓ binding 1A works
 ✓ binding 1A != binding 1B
 ✓ provision 2 works
 ✓ binding 2A works
 ✓ bind 2A does not work for provision 1
 ✓ unbinding 2 works
 ✓ unbinding 1 works
 ✓ deprovision 1 works

10 tests, 0 failures

sudo chmod 744 /etc/hosts
```

**Comment by nickumia-reisys** [comment]
Hmm... apparently the tests are passing now... 🤨 🦑

**Review by mogul — APPROVED** [review]

**Comment by mogul** [comment]
I did a branch reset to remove two unnecessary commits I made (one adding garbage, the other removing it), then force-pushed. Unfortunately now the tests are running long... Been going an hour now when they usually finish in fifteen minutes. 🤔

**Comment by nickumia-reisys** [comment]
I've noticed that the tests take longer to run when it's late at night (EST).  I don't know if they rotate the machines running the actions, reduce the number of machines running or otherwise change things up.  But I've seen a consistently longer run at night 😴

**Pull request merged**
